name: Deploy frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: cd frontend && npm install && npm run build

      - name: Deploy
        uses: paulvstrashnov/yandex-s3-upload-action@main
        with:
          accessKeyId: ${{ secrets.YANDEX_BUCKET_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.YANDEX_BUCKET_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.YANDEX_BUCKET_NAME }}
          localPath: frontend/build
          remotePath: /